feat: update vanilla-zephyr to use Ubuntu 24.04 image

diff --git a/vanilla-zephyr/Dockerfile.ci b/vanilla-zephyr/Dockerfile.ci
--- a/vanilla-zephyr/Dockerfile.ci
+++ b/vanilla-zephyr/Dockerfile.ci
@@ -1,4 +1,4 @@
-FROM ubuntu:22.04
+FROM ubuntu:24.04
 
 ARG ZEPHYR_SDK_VERSION=0.16.8
 ARG ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk-${ZEPHYR_SDK_VERSION}
@@ -7,78 +7,210 @@ ARG MCUBOOT_VERSION=a4eda30f5b0cfd0cf15512be9dcd559239dbfc91
 ARG ZEPHYR_TOOLCHAINS="-t arm-zephyr-eabi -t x86_64-zephyr-elf"
 ARG KITWARE_NINJA_VERSION=1.11.1.g95dee.kitware.jobserver-1
 ENV KITWARE_NINJA_VERSION=$KITWARE_NINJA_VERSION
-ARG CCACHE_VERSION=4.9.1
+ARG CCACHE_VERSION=4.13.2
 ENV CCACHE_VERSION=$CCACHE_VERSION
-ARG DOXYGEN_VERSION=1.14.0
+ARG DOXYGEN_VERSION=1.16.0
 ENV DOXYGEN_VERSION=$DOXYGEN_VERSION
-ARG LLVM_VERSION=16
+ARG LLVM_VERSION=20
 ENV LLVM_VERSION=$LLVM_VERSION
+ARG PROTOC_VERSION=21.7
+ENV PROTOC_VERSION=$PROTOC_VERSION
 ARG WGET_ARGS="-q --show-progress --progress=bar:force:noscroll"
+ARG PYTHON_VENV_PATH=/opt/python/venv
+ARG UBUNTU_MIRROR_ARCHIVE=archive.ubuntu.com/ubuntu
+ARG UBUNTU_MIRROR_SECURITY=security.ubuntu.com/ubuntu
+ARG UBUNTU_MIRROR_PORTS=ports.ubuntu.com/ubuntu-ports
 
 # Set default shell during Docker image build to bash
-SHELL ["/bin/bash", "-c"]
+SHELL [ "/bin/bash", "-euxo", "pipefail", "-c" ]
 
 # Set non-interactive frontend for apt-get to skip any user confirmations
 ENV DEBIAN_FRONTEND=noninteractive
 
 # OS dependencies and packages
-RUN \
-  apt-get -y update && \
-  apt-get -y install --no-install-recommends \
-  ca-certificates \
-  ccache \
-  cmake \
-  device-tree-compiler \
-  dfu-util \
-  file \
-  gcc \
-  git \
-  gperf \
-  jq \
-  lcov \
-  libcairo2-dev \
-  libmagic1 \
-  libsdl2-dev \
-  libgirepository1.0-dev \
-  make \
-  ninja-build \
-  python3-dev \
-  python3-pip \
-  python3-setuptools \
-  python3-tk \
-  python3-wheel \
-  unzip \
-  wget \
-  xz-utils \
-  zip
+RUN <<EOF
+	# Set up custom Ubuntu APT mirrors
+	pushd /etc/apt/sources.list.d
+	cp ubuntu.sources ubuntu.sources.bak
+	sed -i "s#archive.ubuntu.com/ubuntu#${UBUNTU_MIRROR_ARCHIVE}#" ubuntu.sources
+	sed -i "s#security.ubuntu.com/ubuntu#${UBUNTU_MIRROR_SECURITY}#" ubuntu.sources
+	sed -i "s#ports.ubuntu.com/ubuntu-ports#${UBUNTU_MIRROR_PORTS}#" ubuntu.sources
+	popd
 
-# Install multi-lib gcc (x86 only)
-RUN if [ "${HOSTTYPE}" = "x86_64" ]; then \
+	# Enable 32-bit package support for x86-64
+	if [ "${HOSTTYPE}" = "x86_64" ]; then
+		dpkg --add-architecture i386
+	fi
+
+	# Upgrade system packages
+	apt-get -y update
+	apt-get -y upgrade
+
+	# Install base packages
 	apt-get install --no-install-recommends -y \
-		gcc-multilib \
-		g++-multilib \
-	; fi
+		software-properties-common \
+		lsb-release \
+		autoconf \
+		automake \
+		bison \
+		build-essential \
+		ca-certificates \
+		chrpath \
+		cmake \
+		cpio \
+		device-tree-compiler \
+		dfu-util \
+		diffstat \
+		dos2unix \
+		doxygen \
+		file \
+		flex \
+		g++ \
+		gawk \
+		gcc \
+		gcovr \
+		gdb \
+		gdisk \
+		git \
+		git-core \
+		gnupg \
+		gperf \
+		graphviz \
+		help2man \
+		iproute2 \
+		lcov \
+		libcairo2-dev \
+		libfuse3-dev \
+		libglib2.0-dev \
+		libgtk2.0-0 \
+		liblocale-gettext-perl \
+		libncurses5-dev \
+		libpcap-dev \
+		libpopt0 \
+		libsdl1.2-dev \
+		libsdl2-dev \
+		libssl-dev \
+		libtool \
+		libtool-bin \
+		locales \
+		make \
+		net-tools \
+		nodejs \
+		npm \
+		openssh-client \
+		parallel \
+		pkg-config \
+		python3 \
+		python3-dev \
+		python3-pip \
+		python3-ply \
+		python3-setuptools \
+		python3-venv \
+		python-is-python3 \
+		rsync \
+		socat \
+		srecord \
+		sudo \
+		texinfo \
+		unzip \
+		uuid-runtime \
+		valgrind \
+		wget \
+		ovmf \
+		xz-utils \
+		thrift-compiler
 
-# Install i386 packages (x86 only)
-RUN if [ "${HOSTTYPE}" = "x86_64" ]; then \
-	dpkg --add-architecture i386 && \
-	apt-get -y update && \
-	apt-get -y upgrade && \
+	# Install x86-64 image-specific packages
+	if [ "${HOSTTYPE}" = "x86_64" ]; then
+		# Mark `python3` as held because APT otherwise tries to remove it during i386
+		# package installation.
+		apt-mark hold python3 python3-apt
+
+		# Install multi-lib gcc
+		apt-get install --no-install-recommends -y \
+			gcc-multilib \
+			g++-multilib
+
+		# Install 32-bit dependencies
+		apt-get install --no-install-recommends -y \
+			libc6-dbg:i386 \
+			libfuse-dev:i386 \
+			libfuse3-dev:i386 \
+			libsdl2-dev:i386
+	fi
+
+	# Install LLVM and Clang
 	apt-get install --no-install-recommends -y \
-		libsdl2-dev:i386 libfuse-dev:i386 \
-	; fi
+		clang-${LLVM_VERSION} \
+		clang-format-${LLVM_VERSION} \
+		clang-tidy-${LLVM_VERSION} \
+		clang-tools-${LLVM_VERSION} \
+		clangd-${LLVM_VERSION} \
+		libc++-${LLVM_VERSION}-dev \
+		libclang-rt-${LLVM_VERSION}-dev \
+		lld-${LLVM_VERSION} \
+		lldb-${LLVM_VERSION} \
+		llvm-${LLVM_VERSION} \
+		llvm-${LLVM_VERSION}-dev
 
-# Install Python dependencies
-RUN python3 -m pip install -U --no-cache-dir pip && \
-	pip3 install -U --no-cache-dir wheel setuptools && \
-	pip3 install --no-cache-dir pygobject==3.50.0 && \
-	pip3 install --no-cache-dir \
+	# Clean up stale packages
+	apt-get autoremove --purge -y
+
+	# Clean up local repository
+	apt-get clean -y
+	rm -rf /var/lib/apt/lists/*
+
+	# Restore original Ubuntu mirrors
+	pushd /etc/apt/sources.list.d
+	mv -f ubuntu.sources.bak ubuntu.sources
+	popd
+EOF
+
+# Initialise system locale
+RUN locale-gen en_US.UTF-8
+ENV LANG=en_US.UTF-8
+ENV LANGUAGE=en_US:en
+ENV LC_ALL=en_US.UTF-8
+
+# Set up Python virtual environment for Zephyr
+RUN <<EOF
+	# Initialise virtual environment
+	mkdir -p ${PYTHON_VENV_PATH}
+	python3 -m venv ${PYTHON_VENV_PATH}
+
+	# Activate virtual environment for subsequent steps
+	source ${PYTHON_VENV_PATH}/bin/activate
+
+	# Install pip package manager
+	pip install --no-cache-dir --upgrade pip setuptools wheel
+
+	# Install Zephyr requirements
+	pip install --no-cache-dir \
 		-r https://raw.githubusercontent.com/zephyrproject-rtos/zephyr/${ZEPHYR_VERSION}/scripts/requirements.txt \
 		-r https://raw.githubusercontent.com/zephyrproject-rtos/mcuboot/${MCUBOOT_VERSION}/scripts/requirements.txt \
-		GitPython imgtool junitparser junit2html numpy protobuf PyGithub \
-		pylint sh statistics west Sphinx breathe \
-		nrf-regtool>=5.3.0 && \
-	pip3 check
+		-r https://raw.githubusercontent.com/zephyrproject-rtos/trusted-firmware-m/zephyr_tf-m_v2.2.2/tools/requirements.txt \
+		'esptool>=5.0.2' \
+		GitPython \
+		junitparser \
+		junit2html \
+		nrf-regtool~=9.0.1 \
+		numpy \
+		protobuf \
+		grpcio-tools \
+		PyGithub \
+		pylint \
+		sh \
+		statistics \
+		west
+
+	# Run pip check (x86 only for now because it fails on ARM)
+	if [ "${HOSTTYPE}" = "x86_64" ]; then
+		pip check
+	fi
+EOF
+
+# Make Zephyr Python virtual environment available globally
+ENV PATH=${PYTHON_VENV_PATH}/bin:$PATH
 
 # Install Zephyr SDK
 RUN \
@@ -89,62 +221,68 @@ RUN \
   && ${ZEPHYR_SDK_INSTALL_DIR}/setup.sh -c ${ZEPHYR_TOOLCHAINS} \
   && rm ${sdk_file_name}
 
+
 # Install Kitware ninja
-# NOTE: Pre-built Kitware ninja binaries are only available for x86_64 host.
-RUN if [ "${HOSTTYPE}" = "x86_64" ]; then \
-	wget ${WGET_ARGS} https://github.com/Kitware/ninja/releases/download/v${KITWARE_NINJA_VERSION}/ninja-${KITWARE_NINJA_VERSION}_x86_64-linux-gnu.tar.gz && \
-	tar xf ninja-${KITWARE_NINJA_VERSION}_x86_64-linux-gnu.tar.gz -C /opt && \
-	ln -s /opt/ninja-${KITWARE_NINJA_VERSION}_x86_64-linux-gnu/ninja /usr/local/bin && \
-	rm ninja-${KITWARE_NINJA_VERSION}_x86_64-linux-gnu.tar.gz \
-	; fi
+RUN <<EOF
+	NINJA_BASENAME=ninja-${KITWARE_NINJA_VERSION}_${HOSTTYPE}-linux-gnu
+	wget ${WGET_ARGS} https://github.com/Kitware/ninja/releases/download/v${KITWARE_NINJA_VERSION}/${NINJA_BASENAME}.tar.gz
+	tar xf ${NINJA_BASENAME}.tar.gz -C /opt
+	ln -s /opt/${NINJA_BASENAME}/ninja /usr/local/bin
+	rm ${NINJA_BASENAME}.tar.gz
+EOF
 
 # Install ccache
-# NOTE: Pre-built ccache binaries are only available for x86_64 host.
-RUN if [ "${HOSTTYPE}" = "x86_64" ]; then \
-	wget ${WGET_ARGS} https://github.com/ccache/ccache/releases/download/v${CCACHE_VERSION}/ccache-${CCACHE_VERSION}-linux-x86_64.tar.xz && \
-	tar xf ccache-${CCACHE_VERSION}-linux-x86_64.tar.xz -C /opt && \
-	ln -s /opt/ccache-${CCACHE_VERSION}-linux-x86_64/ccache /usr/local/bin && \
-	rm ccache-${CCACHE_VERSION}-linux-x86_64.tar.xz \
-	; fi
+RUN <<EOF
+	CCACHE_BASENAME=ccache-${CCACHE_VERSION}-linux-${HOSTTYPE}-glibc
+	wget ${WGET_ARGS} https://github.com/ccache/ccache/releases/download/v${CCACHE_VERSION}/${CCACHE_BASENAME}.tar.xz
+	tar xf ${CCACHE_BASENAME}.tar.xz -C /opt
+	ln -s /opt/${CCACHE_BASENAME}/ccache /usr/local/bin
+	rm ${CCACHE_BASENAME}.tar.xz
+EOF
 
 # Install Doxygen (x86 only)
 # NOTE: Pre-built Doxygen binaries are only available for x86_64 host.
-RUN if [ "${HOSTTYPE}" = "x86_64" ]; then \
-	wget ${WGET_ARGS} https://downloads.sourceforge.net/project/doxygen/rel-${DOXYGEN_VERSION}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz && \
-	tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz -C /opt && \
-	ln -s /opt/doxygen-${DOXYGEN_VERSION}/bin/doxygen /usr/local/bin && \
-	rm doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz \
-	; fi
+RUN <<EOF
+	if [ "${HOSTTYPE}" = "x86_64" ]; then
+		wget ${WGET_ARGS} "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
+		tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz -C /opt
+		ln -s /opt/doxygen-${DOXYGEN_VERSION}/bin/doxygen /usr/local/bin
+		rm doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
+	fi
+EOF
+
+# Install protobuf-compiler
+RUN <<EOF
+	mkdir -p /opt/protoc
+	cd /opt/protoc
+	PROTOC_HOSTTYPE=$(case $HOSTTYPE in x86_64) echo "x86_64";; aarch64) echo "aarch_64";; esac)
+	wget ${WGET_ARGS} https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-${PROTOC_HOSTTYPE}.zip
+	unzip protoc-${PROTOC_VERSION}-linux-${PROTOC_HOSTTYPE}.zip
+	ln -s /opt/protoc/bin/protoc /usr/local/bin
+	rm -f protoc-${PROTOC_VERSION}-linux-${PROTOC_HOSTTYPE}.zip
+EOF
 
 # Enable CI mode for East and Codechecker. That way East will search for
 # system provided Codechecker and use it.
 ENV EAST_CODECHECKER_CI_MODE=1
 
-RUN pip3 install --no-cache-dir east-tool codechecker
+RUN pip install --no-cache-dir east-tool codechecker
 
-# Install LLVM and Clang
-RUN apt-get -y update && \
-    apt-get install --no-install-recommends -y \
-	software-properties-common \
-	lsb-release \
-	gnupg
 
-RUN wget ${WGET_ARGS} https://apt.llvm.org/llvm.sh && \
-	chmod +x llvm.sh && \
-	./llvm.sh ${LLVM_VERSION} all && \
-	rm -f llvm.sh
 
 RUN apt-get remove -y --purge \
     software-properties-common \
     lsb-release \
     gnupg
 
-# Create simlink for clang-16 and clang-tidy-16, otherwise Codechecker fails
+# Create simlink for clang-20 and clang-tidy-20, otherwise Codechecker fails
 # to find them.
-RUN ln -s /usr/bin/clang-tidy-16 /usr/bin/clang-tidy && \
-    ln -s /usr/bin/clang-16 /usr/bin/clang
+RUN ln -s /usr/bin/clang-tidy-20 /usr/bin/clang-tidy && \
+    ln -s /usr/bin/clang-20 /usr/bin/clang
 
 # Clean up stale packages
-RUN apt-get clean -y && \
-	apt-get autoremove --purge -y && \
+RUN <<EOF
+    apt-get clean -y
+	apt-get autoremove --purge -y
 	rm -rf /var/lib/apt/lists/*
+EOF
